### ISSUE TITLE
tsconfig.json should be on root folder

### ISSUE THREAD

**Issue by raphael22** [Teradata/vantage-ui-template#102]
Hi,

I was trying to use path aliases in my project and it worked but VSC intellisense kept showing a "module not found" error.

``` json
  // tsconfig.app.json

  "compilerOptions": {
    "baseUrl": "src",
    "paths": {
      "@app-services": [ "app-services/index" ]
    },
    ...
```
![screenshot from 2018-07-12 14-30-43](https://user-images.githubusercontent.com/3912356/42633392-acbbbd70-85e0-11e8-861f-9fee533e0877.png)

Moving ```~/src/tsconfig.app.json``` to ```~/tsconfig.json``` resolve this.

**Comment by emoralesb05** [comment]
Not valid anymore since we are repurposing the repo.
