### ISSUE TITLE
'ng serve' failure on Windows

### ISSUE THREAD

**Issue by Delamaine** [Teradata/vantage-ui-template#103]
#### Bug Report

Executing  'ng serve' on windows 10 results in the following error message,

ERROR in ENOENT: no such file or directory, stat 'C:\C\covalent\src\app\app.module.ts'

The angular-cli app resides in 'C:\C\covalent', seems like there is an additional 'C\' prefixed by the ng serve process, not sure where though. Assistance appreciated.

so output is as follows,

**C:\covalent>ng serve
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2018-07-20T04:29:03.325Z
Hash: 761529610e6f4f77920b
Time: 6136ms
chunk {main} main.js, main.js.map (main) 1.88 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 657 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 20.8 kB  [rendered]
chunk {styles} styles.js, styles.js.map (styles) 794 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 325 kB [initial] [rendered]

ERROR in ENOENT: no such file or directory, stat 'C:\C\covalent\src\app\app.module.ts'
i ｢wdm｣: Failed to compile.**

#### What is the expected behavior?

ng serve for quickstart should operate under Windows 

#### Which version of Angular and Material, and which browser and OS does this issue affect?

C:\covalent>ng --version

Angular CLI: 6.0.1
Node: 8.11.3
OS: win32 x64
Angular: 6.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.1
@angular/cli                      6.0.1
@angular/material                 6.0.1
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.1
@schematics/update                0.6.1
ng-packagr                        2.4.2
rxjs                              6.0.0
typescript                        2.7.2
webpack                           4.8.3

##### Other information

none

**Comment by bravecobra** [comment]
I have the same issue here!

**Comment by emoralesb05** [comment]
Not valid anymore since we are repurposing the repo.
