### ISSUE TITLE
Fails to load application - ng serve stops- webpack: Failed to compile

### ISSUE THREAD

**Issue by ksurendra** [Teradata/vantage-ui-template#104]
This repository's issues are reserved for feature requests and bug reports.

#### Bug Report
after doing all the steps as detailed in th docs:

Running "ng serve" fails with these messages

konathal-OSX:covalent-quickstart-develop konathal$ ng serve
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-12-10T21:33:15.938Z                                                       
Hash: c57327f5f1d1069a874f
Time: 6341ms
chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 2.91 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 577 bytes [initial] [rendered]
chunk {scripts} scripts.bundle.js (scripts) 104 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 2.07 MB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 854 kB [initial] [rendered]

_ERROR in src/app/app.module.ts(22,30): error TS2305: Module '"/Users/konathal/Personal/SurenProjects/Angular/teradata/covalent-quickstart-develop/node_modules/@covalent/http/covalent-http"' has no exported member 'IHttpInterceptor'.
src/app/dashboard/dashboard.component.ts(72,24): error TS2339: Property 'query' does not exist on type 'ItemsService'.
src/app/dashboard/dashboard.component.ts(107,23): error TS2339: Property 'query' does not exist on type 'UserService'.
src/app/users/form/form.component.ts(51,49): error TS2339: Property 'get' does not exist on type 'UserService'.
src/app/users/form/form.component.ts(76,33): error TS2339: Property 'create' does not exist on type 'UserService'.
src/app/users/form/form.component.ts(78,33): error TS2339: Property 'update' does not exist on type 'UserService'.
src/app/users/services/user.service.ts(7,10): error TS2305: Module '"/Users/konathal/Personal/SurenProjects/Angular/teradata/covalent-quickstart-develop/node_modules/@covalent/http/covalent-http"' has no exported member 'HttpInterceptorService'.
src/app/users/services/user.service.ts(7,34): error TS2305: Module '"/Users/konathal/Personal/SurenProjects/Angular/teradata/covalent-quickstart-develop/node_modules/@covalent/http/covalent-http"' has no exported member 'RESTService'.
src/app/users/users.component.ts(44,44): error TS2339: Property 'query' does not exist on type 'UserService'.
src/app/users/users.component.ts(66,31): error TS2339: Property 'delete' does not exist on type 'UserService'.
src/config/interceptors/request.interceptor.ts(3,10): error TS2305: Module '"/Users/konathal/Personal/SurenProjects/Angular/teradata/covalent-quickstart-develop/node_modules/@covalent/http/covalent-http"' has no exported member 'IHttpInterceptor'.
src/services/alerts.service.ts(3,10): error TS2305: Module '"/Users/konathal/Personal/SurenProjects/Angular/teradata/covalent-quickstart-develop/node_modules/@covalent/http/covalent-http"' has no exported member 'HttpInterceptorService'.
src/services/items.service.ts(3,10): error TS2305: Module '"/Users/konathal/Personal/SurenProjects/Angular/teradata/covalent-quickstart-develop/node_modules/@covalent/http/covalent-http"' has no exported member 'HttpInterceptorService'.
src/services/items.service.ts(3,34): error TS2305: Module '"/Users/konathal/Personal/SurenProjects/Angular/teradata/covalent-quickstart-develop/node_modules/@covalent/http/covalent-http"' has no exported member 'RESTService'.
src/services/products.service.ts(3,10): error TS2305: Module '"/Users/konathal/Personal/SurenProjects/Angular/teradata/covalent-quickstart-develop/node_modules/@covalent/http/covalent-http"' has no exported member 'HttpInterceptorService'._

webpack: Failed to compile.

##### Screenshots or link to CodePen/Plunker/JSfiddle
![screen shot 2018-12-10 at 3 33 18 pm](https://user-images.githubusercontent.com/902972/49763019-240ba300-fc91-11e8-9929-a366bcee7c29.png)

#### What is the expected behavior?
Application build and eploy using "ng serve"

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Angular CLI: 1.7.3
Node: 10.5.0
OS: darwin x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 6.4.7
@angular/cli: 1.7.3
@angular/material: 6.4.7
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.7.2
webpack: 3.11.0
konathal-OSX:covalent-quickstart-develop konathal$ 

##### Other information
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by duxy2002** [comment]
same issue!

**Comment by emoralesb05** [comment]
There are breaking changes that were done with covalent/http for 2.0.0.. please check them in our changelog https://github.com/Teradata/covalent/blob/develop/docs/CHANGELOG.md#breaking-changes

**Comment by emoralesb05** [comment]
Not valid anymore since we are repurposing the repo.
