### ISSUE TITLE
Mock-api scripts fail for yarn installation but not npm installation

### ISSUE THREAD

**Issue by stevenov7** [Teradata/vantage-ui-template#107]
### Do you want to request a *feature* or report a *bug*?
bug

#### Bug Report

The mock-api scripts have an issue the `start-api` and `stop-api` scripts work when `npm install` is used but not when `yarn reinstall` is used). Further investigation and communication is needed to decide what path we want to take here. 

<img width="407" alt="screen shot 2019-01-07 at 10 49 36 am" src="https://user-images.githubusercontent.com/24550592/50790394-a9c04580-1273-11e9-9ff8-917abee779ed.png">
<img width="521" alt="screen shot 2019-01-07 at 10 50 11 am" src="https://user-images.githubusercontent.com/24550592/50790395-aa58dc00-1273-11e9-8735-832e3585b9c9.png">

#### What is the expected behavior?
After running `yarn reinstall` or `yarn install` a developer should be able to run `yarn start-api` successfully.

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Only tested this on macOS Mojave v10.14 though the command line in VSCode v1.30.1

**Comment by jeremysmartt** [comment]
need to update documentation to not reference yarn

**Comment by emoralesb05** [comment]
Not valid anymore since we are repurposing the repo.
