### ISSUE TITLE
Build on production, can't map hammerjs

### ISSUE THREAD

**Issue by Germanaz0** [Teradata/vantage-ui-template#15]
#### Bug Report

When I use `ng build -prod` and upload everything where is on my dist/ folder to a server, I am getting the following error:

`DevTools failed to parse SourceMap: http://mysite.com/hammer.min.js.map`

And the same error happens with showdown.
#### Which version of Angular and Material, and which browser and OS does this issue affect?

angular-cli: 1.0.0-beta.15
node: 7.0.0
webpack: 2.1.0-beta.22
os: darwin x64

I'm using covalent 8.0

**Comment by emoralesb05** [comment]
Not valid anymore since we are repurposing the repo.
