### ISSUE TITLE
Use feature modules

### ISSUE THREAD

**Issue by aciccarello** [Teradata/vantage-ui-template#19]
#### Feature Request

To align better with the Angular 2 Style Guide, the quickstart should have [feature modules](https://angular.io/docs/ts/latest/guide/style-guide.html#!#04-09) for each directory under the app folder.

#### What is the motivation / use case for changing the behavior?

Loading all components into a single app module is not scalable. Demonstrating how to create feature modules would make it easier for users to adapt the quickstart to their needs.

**Comment by aciccarello** [comment]
Using a shared module and a core module (also in the style guide) would be helpful as well. In general I think it would be good for quickstart to be set up with best practices at the start (not just show how to use the great covalent features).

**Comment by d3viant0ne** [comment]
It would also facilitate the ability to leverage the CLIs lazyload / bundling which is also beneficial when scaling out an app.

**Comment by jeremysmartt** [comment]
closing issue, no longer needed
