### ISSUE TITLE
Angular Universal with AOT and without AOT Server rendering needed

### ISSUE THREAD

**Issue by imVinayPandya** [Teradata/vantage-ui-template#40]
i am new too angular 2, i dont have idea about Angular Universal. i have gone through many articles and universal-cli but i got confused.

### Do you want to request a *feature* or report a *bug*?
feature
#### Feature Request
please make this quick start production ready with Angular Universal, so noob developer like me can easily make production ready app.

**Comment by hardikpatel-1** [comment]
I am also facing the same issue and i also have same suggestions

**Comment by emoralesb05** [comment]
The problem is that covalent doest not support SSR yet, once this is possible we will update the quickstart.

**Comment by hardikpatel-1** [comment]
There is no need for SSR.

Even They can make this quick start production ready Mock(Json) data also.

**Comment by imVinayPandya** [comment]
@emoralesb05 any updates SSR??

**Comment by jeremysmartt** [comment]
Closing this issue, Covalent support Ivy Rendering
