### ISSUE TITLE
Data table rows don't always display with pagination and searching

### ISSUE THREAD

**Issue by jraadt** [Teradata/vantage-ui-template#44]
#### Bug Report

Copy from [https://github.com/Teradata/covalent/issues/366](https://github.com/Teradata/covalent/issues/366)

With pagination enabled on a data table, if you page and then start searching and it returns less items that can fit on a page, it says there are no results.  But there are just no results on the page you currently are on.  It should flip you back to page 1 so you can see your search results.

To reproduce:
1) Go to the following quickstart: https://teradata.github.io/covalent-quickstart/#/product/stats
2) In the Product Stats table sort the product table in ascending order.
3) Page to the 2nd page.
4) Search for Logs.
5) It says there are no results, but the results are on page 1.  Confusing for the end user.

**Comment by emoralesb05** [comment]
Not valid anymore since we are repurposing the repo.
