### ISSUE TITLE
ng test 

### ISSUE THREAD

**Issue by kthomas182** [Teradata/vantage-ui-template#48]
ng test fails on standard build of covalent-quickstart 

![screenshot at mar 01 16-47-06](https://cloud.githubusercontent.com/assets/5391542/23484923/bd0f3046-fe9e-11e6-9871-4dbc98e89088.png)

**Comment by BartNetJS** [comment]
same here (Windows 10)

**Comment by msaysell** [comment]
same..

**Comment by msaysell** [comment]
So I've been looking through this anyway to try and solve my own issues with ng test and it appears as though the commit:

88cc39845eeca3abb7faf3ee59f48629238fd337

Removed th `item-list` and `user-list` from the html as well as the `items` and `users` from the component so the tests will never pass hence when the test does `element.querySelector('.item-list')` it gets null back which isn't "truthy", quick fix for anyone interested is just to delete the tests from `dashboard-product.component.spec.ts` (lines 99-107) but I'd hardly call that a fix

**Comment by aqupriyanka** [comment]
Added test cases and assigned to @philgetz for review
