### ISSUE TITLE
Type script files in @covalent node_module

### ISSUE THREAD

**Issue by cissecedric** [Teradata/vantage-ui-template#50]
#### Bug Report
I can't find typeScript files in @covalent (v1.0.0-beta.2) node_modules anymore, do you plan to put those files back in next releases?
for example, dialog.module.ts and dialog.component.ts are missing in the picture below :
![image](https://cloud.githubusercontent.com/assets/12851286/23681023/98e9d2e0-038d-11e7-9679-e319aac6ab24.png)

##### Other information
Typscript files were present in @covalent previous versions

Thanks,

**Comment by emoralesb05** [comment]
So the CLI has an issue (maybe bug), where it fails its `aot` build when there are `ts` files in the `node_modules` dir.

We might return the `ts` files later on, but honestly you shouldnt need to worry about them and just use either the `js` files or the `umd.js` file.

**Comment by cissecedric** [comment]
I used them to add my own features in the stepper component, it was a lot easier than adding them in js files. Maybe I shouldn't use the quickstart, but I should directly use "covalent" instead, so that I will get ts files ?

**Comment by emoralesb05** [comment]
The better way is to just extend the classes or wrap the components inside your project, instead of modifying the `node_modules`. 

Since in reality when you do `npm i` from scratch in a diff env.. you need to replace/add the files again. Its not a good practice to modify anything inside `node_modules`.

**Comment by cissecedric** [comment]
After a few days, I must admit I can't figure out how to extend stepper classes.
Could you please give me a way to do this ?
