### ISSUE TITLE
Stepper methods calls doesn't work

### ISSUE THREAD

**Issue by cissecedric** [Teradata/vantage-ui-template#80]
Hi,

I think this is a bug report

#### Bug Report
Stepper methods doesn't work for TDStepComponent, toogle(), nor open() and close()
for exemple I tried adding a stepper in the userformcomponent please see the code in files below.
The line nextStep.toggle() in form.component.ts should trigger a toggle but it doesn't
I also tried to mix curStep.close() and nextStep.open().... same problems.
Thank you for your help

[users.module.ts.txt](https://github.com/Teradata/covalent-quickstart/files/1216713/users.module.ts.txt)

[form.component.html.txt](https://github.com/Teradata/covalent-quickstart/files/1216710/form.component.html.txt)

[form.component.ts.txt](https://github.com/Teradata/covalent-quickstart/files/1216711/form.component.ts.txt)

Regards

**Comment by jotatoledo** [comment]
Please create a plnkr or similar to reproduce your problem, as that is not part of the original user form component.

**Comment by cissecedric** [comment]
Thank you for your answer Jota, you made me do my first plunkr ;-)
I used your base plunkr and here is the result : http://plnkr.co/edit/9EFV5qCt4zBqxahHRPIK?p=preview
Well I still don't understand why it works in this base plunkr, but it doesn't when I do the same in the quickstart... I'l check again what are the differences and let you know, may be versions are different between the plunk and the quickstart..

**Comment by jotatoledo** [comment]
Versions are indeed different, maybe its related to it. Its hard to tell, as u added new behavior to the component.

For now I wont try to reproduce your problem in the quickstart repo, as it goes away from the original design of it.

**Comment by cissecedric** [comment]
I've just found the problem when I comment the following line in the userFormComponent (where I tried to add ths stepper...)
"let user: IUser = await this._userService.get(this.id).toPromise();"
everything works as expected.
So there is a kind of incompatibility between the stepper and this part of code (await... toPromise())

liket this, stepper works fine:

......
next(i: number): void {
    let curStep: TdStepComponent = this.stepComponentComponentList[i];
    let nextStep: TdStepComponent = this.stepComponentComponentList[i + 1];

    curStep.state = StepState.Complete;
    nextStep.toggle();
  }

  async load(): Promise<void> {
    try {
      this._loadingService.register('user.form');
      // let user: IUser = await this._userService.get(this.id).toPromise();
      // this.displayName = user.displayName;
      // this.email = user.email;
      // this.admin = (user.siteAdmin === 1 ? true : false);
    } 
    catch (error) {
      this._dialogService.openAlert({ message: 'There was an error loading the user' });
    } 
    finally {
      this._loadingService.resolve('user.form');
    }
  }
......

**Comment by emoralesb05** [comment]
Not valid anymore since we are repurposing the repo.
