### ISSUE TITLE
invalid mock-api schemas

### ISSUE THREAD

**Issue by mikehutter** [Teradata/vantage-ui-template#83]
### Do you want to request a *feature* or report a *bug*?
Bug

#### Bug Report
It appears that the schemas for the mock-api might be outdated?

The current schema in users.yaml is:
```
displayName: _firstname_ _lastname_
id: _firstname_._lastname_
email: _firstname_._lastname_@_company_.com
created: _createdtimestamp_
lastAccess: _itemtimestamp_
siteAdmin: _admin_
```
which produces:

`[{"created":"_createdtimestamp_","displayName":"_firstname_ _lastname_","email":"_firstname_._lastname_@_company_.com","id":"_firstname_._lastname_","lastAccess":"_itemtimestamp_","siteAdmin":"_admin_"},{"created":"_createdtimestamp_","displayName":"_firstname_ _lastname_","email":"_firstname_._lastname_@_company_.com","id":"_firstname_._lastname_","lastAccess":"_itemtimestamp_","siteAdmin":"_admin_"},{"created":"_createdtimestamp_","displayName":"_firstname_ _lastname_","email":"_firstname_._lastname_@_company_.com","id":"_firstname_._lastname_","lastAccess":"_itemtimestamp_","siteAdmin":"_admin_"},{"created":"_createdtimestamp_","displayName":"_firstname_ _lastname_","email":"_firstname_._lastname_@_company_.com","id":"_firstname_._lastname_","lastAccess":"_itemtimestamp_","siteAdmin":"_admin_"},{"created":"_createdtimestamp_","displayName":"_firstname_ _lastname_","email":"_firstname_._lastname_@_company_.com","id":"_firstname_._lastname_","lastAccess":"_itemtimestamp_","siteAdmin":"_admin_"}]`

The documentation [here](https://ilsiepotamus.gitbooks.io/covalent-data/content/api/crud.html) shows a different syntax:

```
displayName: {{.firstname}} {{.lastname}}
id: {{toLower(.firstname)}}.{{toLower(.lastname)}}
email: {{toLower(.firstname)}}.{{toLower(.lastname)}}@{{.company}}.com
created: {{.createdtimestamp}}
lastAccess: {{.itemtimestamp}}
siteAdmin: {{randomNumber(1)}}
```

which produces:

`[{"created":"10/01/2015 11:05 AM","displayName":"Aaron Burke","email":"aaron.burke@teradata.com","id":"aaron.burke","lastAccess":"7/23/2016 12:05 AM","siteAdmin":0},{"created":"10/01/2015 11:06 AM","displayName":"Olive Park","email":"olive.park@hotmail.com","id":"olive.park","lastAccess":"7/23/2016 12:05 AM","siteAdmin":0},{"created":"10/01/2015 11:05 AM","displayName":"Benjamin Davidson","email":"benjamin.davidson@gmail.com","id":"benjamin.davidson","lastAccess":"7/23/2016 12:05 AM","siteAdmin":0},{"created":"10/01/2015 11:07 AM","displayName":"Edward Gonzales","email":"edward.gonzales@outlook.com","id":"edward.gonzales","lastAccess":"7/23/2016 12:05 AM","siteAdmin":0},{"created":"10/01/2015 11:06 AM","displayName":"Carl Kim","email":"carl.kim@yahoo.com","id":"carl.kim","lastAccess":"7/23/2016 12:05 AM","siteAdmin":0}]`

The other two (features.yaml and items.yaml) suffer the same issue.  I'd just fix it and create a pull request, but I'm not sure how...

**Comment by emoralesb05** [comment]
Not valid anymore since we are repurposing the repo.
