### ISSUE TITLE
You have to be inside an angular-cli project in order to use the serve command

### ISSUE THREAD

**Issue by richardcatlin** [Teradata/vantage-ui-template#85]
I ran all the steps with a clean install of node and npm, and got this error on ng serve from the covalent-quickstart directory:

You have to be inside an angular-cli project in order to use the serve command

**Comment by emoralesb05** [comment]
Whats the angular/cli version you have installed?

**Comment by enzonotario** [comment]
you have to install `@angular/cli` instead of `angular-cli@latest` (that is what the readme says). It's the same problem that I commented here: #51

**Comment by emoralesb05** [comment]
Not valid anymore since we are repurposing the repo.
