### ISSUE TITLE
Slim down the quickstart or make it clear what can be removed

### ISSUE THREAD

**Issue by enzeart** [Teradata/vantage-ui-template#86]
I'm in the process of trying to use the quickstart for a new project, but it's difficult to figure out what can be removed without breaking some aspect of the project structure. It would be nice if the quickstart was more minimalistic and/or provided instructions outlining the best way to strip out example elements

**Comment by jeremysmartt** [comment]
yes, this is something we have been talking about doing, having more of a empty template quickstart rather than a full app running.

**Comment by rafszul** [comment]
@jeremysmartt hi there, any updates on this one?

**Comment by emoralesb05** [comment]
We were just upgrading the quickstart to latest covalent, and now we are about to strip it down in the next couple of weeks

**Comment by emoralesb05** [comment]
Not valid anymore since we are repurposing the repo.
