### ISSUE TITLE
The quickstart is not compatible with the version ^1.0.0-beta.7

### ISSUE THREAD

**Issue by MROALI** [Teradata/vantage-ui-template#88]
Hi all,

It seems that the example is not compatible with beta 7. for example 
1-  the menu button is not showing (as in your documentation we must add   the following which is not present in the quickstart. 
<button md-icon-button [tdLayoutToggle]="true"> <md-icon>menu</md-icon></button>
). 

2- The logo is not aligned so i needed to add the folowwin in my css to align it : 
.mat-icon.md-icon-logo {
  height: auto;
  width: 100px
}

Can you please cofirm me if the quickstart is compatible or not? 

Thankyou in advance

**Comment by kyleledbetter** [comment]
Sorry about that, we're planning these Quickstart updates after the beta.8 release later today, with clear commits for clear upgrade paths:

1. beta.5 - beta.6
2. beta.6 - beta.7
3. beta.7 - beta.8
4. refactor and simplify Quickstart

**Comment by arv10singh** [comment]
Hi All , 
In this time Covalent 1.0.0-rc.0  is released.  Can you upgrade.

**Comment by adeptues** [comment]
+1

**Comment by darknessm0404** [comment]
+2

**Comment by jotatoledo** [comment]
Stop with the useless comments. Either wait or fork the rep, update and submit a pr.

**Comment by emoralesb05** [comment]
Not valid anymore since we are repurposing the repo.
