### ISSUE TITLE
I can't see fab and toolbar after upgrading.

### ISSUE THREAD

**Issue by gbrigens** [Teradata/vantage-ui-template#90]
Main covalent was upgraded to `"@covalent/core": "^1.0.0-beta.8-1",` which has support for `"@angular/material": "^2.0.0-beta.12",` and `"@angular/cdk": "^2.0.0-beta.12",`. I upgraded my app but got this error were I can not see `<div mat-toolbar td-toolbar-content layout="row" layout-align="start center" flex>` and `<a mat-fab color="accent" class="mat-fab-bottom-right" [routerLink]="['add']">
  <mat-icon>add</mat-icon>
</a>
![screen shot 2017-10-13 at 9 44 51 am](https://user-images.githubusercontent.com/4210156/31533491-3555de84-affb-11e7-8342-56f49df4173d.png)
`

**Comment by kyleledbetter** [comment]
sorry just saw this (we mainly keep an eye on the [main repo issues](https://github.com/teradata/covalent/issues))

try adding class of `z-3` to the FAB, material added z-index to the sidenav and it pushes down a FAB

on the toolbar we had changes in recent releases, please compare your toolbar code to the demos in the layouts https://teradata.github.io/covalent/#/layouts

**Comment by jeremysmartt** [comment]
Also checkout out our upgrade wikis.  Listed are items we found needing to be done in a consolidated format.  You can see the z-3 one listed here:
https://github.com/Teradata/covalent/wiki/Upgrade-from-1.0.0-beta.7-to-1.0.0-beta.8.1
