### ISSUE TITLE
Node 9 Compatibility

### ISSUE THREAD

**Issue by natejgardner** [Teradata/vantage-ui-template#91]
On `yarn install`, the following message is displayed:

`error covalent-quickstart@1.0.0: The engine "node" is incompatible with this module. Expected version ">4.4 < 7".`

Is there support for Node 9? Of course I can work around this by editing the default package.json but I'm curious if there is some incompatibility I should be aware of.

**Comment by emoralesb05** [comment]
Technically there shouldnt be any issues, but we keep the same restriction as the angular project do just in case https://github.com/angular/angular/blob/master/package.json#L11. So if anybody wants to go around that, its up to that user.

**Comment by luchillo17** [comment]
If that's so, why not just a warning instead of an error? i stumbled into this for a few hours before finding this issue, because it blocks install.
